version: '3.4'

services:

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Identity.Api/Dockerfile
    depends_on:
      - mssqlsrv

  academic.api:
    image: ${DOCKER_REGISTRY-}academicapi
    build:
      context: .
      dockerfile: Academic.API/Dockerfile
    environment:
      ASPNETCORE_ConnectionStrings__MSSQL: "Server=mssqlsrv,1433;Database=AttendanceTaking.Services.AcademicDb;User Id=sa;Password=Password123"
    depends_on:
      - mssqlsrv

#ports: host:container
  mssqlsrv:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: attendanceDB
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
