// <auto-generated />
using System;
using Academic.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Academic.Infrastructure.Migrations
{
    [DbContext(typeof(AcademicDbContext))]
    [Migration("20201004024849_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Academic.Domain.CourseAllocationAggregate.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<int?>("CourseGroupId")
                        .HasColumnName("CourseGroupId1")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("_courseGroupId")
                        .HasColumnName("CourseGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseGroupId");

                    b.ToTable("courses","academic");
                });

            modelBuilder.Entity("Academic.Domain.CourseAllocationAggregate.CourseGroup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.HasKey("Id");

                    b.ToTable("coursegroup","academic");
                });

            modelBuilder.Entity("Academic.Domain.CourseAllocationAggregate.Course", b =>
                {
                    b.HasOne("Academic.Domain.CourseAllocationAggregate.CourseGroup", "CourseGroup")
                        .WithMany()
                        .HasForeignKey("CourseGroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
